groups:

- name: all
  jobs:
  - update-buildpacks-java
  - test-buildpack-java
  - notify-operator-java
  - update-buildpacks-prod-java
  - update-buildpacks-go
  - test-buildpack-go
  - notify-operator-go
  - update-buildpacks-prod-go
  - update-buildpacks-nodejs
  - test-buildpack-nodejs
  - notify-operator-nodejs
  - update-buildpacks-prod-nodejs

- name: update-buildpacks-java
  jobs:
  - update-buildpacks-java
  - test-buildpack-java
  - notify-operator-java
  - update-buildpacks-prod-java

- name: update-buildpacks-go
  jobs:
  - update-buildpacks-go
  - test-buildpack-go
  - notify-operator-go
  - update-buildpacks-prod-go

- name: update-buildpacks-nodejs
  jobs:
  - update-buildpacks-nodejs
  - test-buildpack-nodejs
  - notify-operator-nodejs
  - update-buildpacks-prod-nodejs


resource_types:

- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

- name: email
  type: docker-image
  source:
    repository: pcfseceng/email-resource

resources:

- name: pipeline-run-id
  type: semver
  source:
    bucket: {{aws_s3_bucket_name}}
    key: buildpack_trigger_run_id
    initial_version: 1.0.0
    access_key_id: {{aws_s3_key}}
    secret_access_key: {{aws_s3_secret}}

- name: pipeline-triggered-buildpack
  type: s3
  source:
    bucket: {{aws_s3_bucket_name}}
    regexp: triggered_runs/buildpack-(.*).id
    access_key_id: {{aws_s3_key}}
    secret_access_key: {{aws_s3_secret}}

- name: notify-operator
  type: email
  source:
    smtp:
      host: {{smtp_host}}
      port: {{smtp_port}}
      username: {{smtp_username}}
      password: {{smtp_password}}
    from: c0-day2-buildpacks@customer0.net
    to: [ "mglynn@pivotal.io" ]

- name: concourse-day2-buildpacks
  type: git
  source:
    uri: https://github.com/c0-ops/concourse-day2-buildpacks.git
    branch: master

- name: java-buildpack-release
  type: bosh-io-release
  check_every: 2h
  source:
    repository: cloudfoundry/java-buildpack-release

- name: go-buildpack-release
  type: bosh-io-release
  check_every: 2h
  source:
    repository: cloudfoundry/go-buildpack-release

- name: nodejs-buildpack-release
  type: bosh-io-release
  check_every: 2h
  source:
    repository: cloudfoundry/go-buildpack-release


jobs:
################################
#### Java Offline Buildpack ####
################################
- name: update-buildpacks-java
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: concourse-day2-buildpacks
      trigger: false
    - get: java-buildpack-release
      trigger: true
    - get: pipeline-run-id
      params: {bump: major}
  - put: pipeline-run-id
    params: {file: pipeline-run-id/number}
  - task: update-buildpacks
    config:
      platform: linux
      image: docker:///virtmerlin/c0-worker
      inputs:
        - name: concourse-day2-buildpacks
        - name: java-buildpack-release
        - name: pipeline-run-id
      outputs:
        - name: run-info
      run:
        path: concourse-day2-buildpacks/ci/tasks/update/update-buildpacks.sh
      params:
        buildpack: "java_buildpack_offline"
        sandbox_cf_api: {{sandbox_cf_api}}
        sandbox_cf_user: {{sandbox_cf_user}}
        sandbox_cf_password: {{sandbox_cf_password}}
        pivnet_api_token: {{pivnet_api_token}}
  - put: pipeline-triggered-buildpack
    params:
      file: run-info/buildpack-*.id
- name: test-buildpack-java
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: concourse-day2-buildpacks
      trigger: false
    - get: java-buildpack-release
      trigger: true
      passed: [update-buildpacks-java]
    - get: pipeline-run-id
      passed: [update-buildpacks-java]
      trigger: true
    - get: pipeline-triggered-buildpack
      passed: [update-buildpacks-java]
  - task: test-buildpack-java
    config:
      platform: linux
      image: docker:///virtmerlin/c0-worker
      inputs:
        - name: concourse-day2-buildpacks
        - name: java-buildpack-release
      run:
        path: concourse-day2-buildpacks/ci/tasks/test/test-buildpacks.sh
      params:
        buildpack: "java_buildpack_offline"
        sandbox_cf_api: {{sandbox_cf_api}}
        sandbox_cf_user: {{sandbox_cf_user}}
        sandbox_cf_password: {{sandbox_cf_password}}
# Notify Operator
- name: notify-operator-java
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - get: pipeline-run-id
    trigger: true
    passed: ["test-buildpack-java"]
  - get: concourse-day2-buildpacks
    trigger: false
  - get: pipeline-triggered-buildpack
    passed: ["test-buildpack-java"]
  - task: notify-operator
    config:
      platform: linux
      image: docker:///virtmerlin/c0-worker
      inputs:
        - name: concourse-day2-buildpacks
        - name: pipeline-triggered-buildpack
      outputs:
        - name: run-info
      run:
       path: concourse-day2-buildpacks/ci/tasks/notify/notify-operator.sh
  - put: notify-operator
    params:
      subject: run-info/subject
      body: run-info/body
# Apply to Prod if so desired
- name: update-buildpacks-prod-java
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - get: pipeline-run-id
    passed: [notify-operator-java]
    trigger: true
  - get: pipeline-triggered-buildpack
    passed: [notify-operator-java]
  - get: concourse-day2-buildpacks
  - task: update-buildpacks-prod-java
    config:
      platform: linux
      image: docker:///virtmerlin/c0-worker
      inputs:
        - name: concourse-day2-buildpacks
        - name: pipeline-triggered-buildpack
      outputs:
        - name: run-info
      run:
       path: concourse-day2-buildpacks/ci/tasks/prod/update-buildpacks-prod.sh
      params:
        buildpack: "java_buildpack_offline"
        prod_cf_api: {{sandbox_cf_api}}
        prod_cf_user: {{sandbox_cf_user}}
        prod_cf_password: {{sandbox_cf_password}}
        pivnet_api_token: {{pivnet_api_token}}

################################
####   Golang Buildpack     ####
################################
- name: update-buildpacks-go
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: concourse-day2-buildpacks
      trigger: false
    - get: go-buildpack-release
      trigger: true
    - get: pipeline-run-id
      params: {bump: major}
  - put: pipeline-run-id
    params: {file: pipeline-run-id/number}
  - task: update-buildpacks
    config:
      platform: linux
      image: docker:///virtmerlin/c0-worker
      inputs:
        - name: concourse-day2-buildpacks
        - name: go-buildpack-release
        - name: pipeline-run-id
      outputs:
        - name: run-info
      run:
        path: concourse-day2-buildpacks/ci/tasks/update/update-buildpacks.sh
      params:
        buildpack: "go_buildpack"
        sandbox_cf_api: {{sandbox_cf_api}}
        sandbox_cf_user: {{sandbox_cf_user}}
        sandbox_cf_password: {{sandbox_cf_password}}
        pivnet_api_token: {{pivnet_api_token}}
  - put: pipeline-triggered-buildpack
    params:
      file: run-info/buildpack-*.id
- name: test-buildpack-go
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: concourse-day2-buildpacks
      trigger: false
    - get: go-buildpack-release
      trigger: true
      passed: [update-buildpacks-go]
    - get: pipeline-run-id
      passed: [update-buildpacks-go]
      trigger: true
    - get: pipeline-triggered-buildpack
      passed: [update-buildpacks-go]
  - task: test-buildpack-java
    config:
      platform: linux
      image: docker:///virtmerlin/c0-worker
      inputs:
        - name: concourse-day2-buildpacks
        - name: go-buildpack-release
      run:
        path: concourse-day2-buildpacks/ci/tasks/test/test-buildpacks.sh
      params:
        buildpack: "go_buildpack"
        sandbox_cf_api: {{sandbox_cf_api}}
        sandbox_cf_user: {{sandbox_cf_user}}
        sandbox_cf_password: {{sandbox_cf_password}}
# Notify Operator
- name: notify-operator-go
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - get: pipeline-run-id
    trigger: true
    passed: ["test-buildpack-go"]
  - get: concourse-day2-buildpacks
    trigger: false
  - get: pipeline-triggered-buildpack
    passed: ["test-buildpack-go"]
  - task: notify-operator
    config:
      platform: linux
      image: docker:///virtmerlin/c0-worker
      inputs:
        - name: concourse-day2-buildpacks
        - name: pipeline-triggered-buildpack
      outputs:
        - name: run-info
      run:
       path: concourse-day2-buildpacks/ci/tasks/notify/notify-operator.sh
  - put: notify-operator
    params:
      subject: run-info/subject
      body: run-info/body
# Apply to Prod if so desired
- name: update-buildpacks-prod-go
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - get: pipeline-run-id
    passed: [notify-operator-go]
    trigger: true
  - get: pipeline-triggered-buildpack
    passed: [notify-operator-go]
  - get: concourse-day2-buildpacks
  - task: update-buildpacks-prod-java
    config:
      platform: linux
      image: docker:///virtmerlin/c0-worker
      inputs:
        - name: concourse-day2-buildpacks
        - name: pipeline-triggered-buildpack
      outputs:
        - name: run-info
      run:
       path: concourse-day2-buildpacks/ci/tasks/prod/update-buildpacks-prod.sh
      params:
        buildpack: "go_buildpack"
        prod_cf_api: {{sandbox_cf_api}}
        prod_cf_user: {{sandbox_cf_user}}
        prod_cf_password: {{sandbox_cf_password}}
        pivnet_api_token: {{pivnet_api_token}}

################################
####   Node Buildpack     ####
################################
- name: update-buildpacks-nodejs
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: concourse-day2-buildpacks
      trigger: false
    - get: nodejs-buildpack-release
      trigger: true
    - get: pipeline-run-id
      params: {bump: major}
  - put: pipeline-run-id
    params: {file: pipeline-run-id/number}
  - task: update-buildpacks
    config:
      platform: linux
      image: docker:///virtmerlin/c0-worker
      inputs:
        - name: concourse-day2-buildpacks
        - name: nodejs-buildpack-release
        - name: pipeline-run-id
      outputs:
        - name: run-info
      run:
        path: concourse-day2-buildpacks/ci/tasks/update/update-buildpacks.sh
      params:
        buildpack: "nodejs_buildpack"
        sandbox_cf_api: {{sandbox_cf_api}}
        sandbox_cf_user: {{sandbox_cf_user}}
        sandbox_cf_password: {{sandbox_cf_password}}
        pivnet_api_token: {{pivnet_api_token}}
  - put: pipeline-triggered-buildpack
    params:
      file: run-info/buildpack-*.id
- name: test-buildpack-nodejs
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: concourse-day2-buildpacks
      trigger: false
    - get: nodejs-buildpack-release
      trigger: true
      passed: [update-buildpacks-nodejs]
    - get: pipeline-run-id
      passed: [update-buildpacks-nodejs]
      trigger: true
    - get: pipeline-triggered-buildpack
      passed: [update-buildpacks-nodejs]
  - task: test-buildpack-java
    config:
      platform: linux
      image: docker:///virtmerlin/c0-worker
      inputs:
        - name: concourse-day2-buildpacks
        - name: nodejs-buildpack-release
      run:
        path: concourse-day2-buildpacks/ci/tasks/test/test-buildpacks.sh
      params:
        buildpack: "nodejs_buildpack"
        sandbox_cf_api: {{sandbox_cf_api}}
        sandbox_cf_user: {{sandbox_cf_user}}
        sandbox_cf_password: {{sandbox_cf_password}}
# Notify Operator
- name: notify-operator-nodejs
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - get: pipeline-run-id
    trigger: true
    passed: ["test-buildpack-nodejs"]
  - get: concourse-day2-buildpacks
    trigger: false
  - get: pipeline-triggered-buildpack
    passed: ["test-buildpack-nodejs"]
  - task: notify-operator
    config:
      platform: linux
      image: docker:///virtmerlin/c0-worker
      inputs:
        - name: concourse-day2-buildpacks
        - name: pipeline-triggered-buildpack
      outputs:
        - name: run-info
      run:
       path: concourse-day2-buildpacks/ci/tasks/notify/notify-operator.sh
  - put: notify-operator
    params:
      subject: run-info/subject
      body: run-info/body
# Apply to Prod if so desired
- name: update-buildpacks-prod-nodejs
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - get: pipeline-run-id
    passed: [notify-operator-nodejs]
    trigger: true
  - get: pipeline-triggered-buildpack
    passed: [notify-operator-nodejs]
  - get: concourse-day2-buildpacks
  - task: update-buildpacks-prod-java
    config:
      platform: linux
      image: docker:///virtmerlin/c0-worker
      inputs:
        - name: concourse-day2-buildpacks
        - name: pipeline-triggered-buildpack
      outputs:
        - name: run-info
      run:
       path: concourse-day2-buildpacks/ci/tasks/prod/update-buildpacks-prod.sh
      params:
        buildpack: "nodejs_buildpack"
        prod_cf_api: {{sandbox_cf_api}}
        prod_cf_user: {{sandbox_cf_user}}
        prod_cf_password: {{sandbox_cf_password}}
        pivnet_api_token: {{pivnet_api_token}}
