groups:

- name: all
  jobs:
  - update-buildpacks-java
  - test-buildpack-java

- name: update-buildpacks-java
  jobs:
  - update-buildpacks-java
  - test-buildpack-java


resource_types:

- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:

- name: concourse-day2-buildpacks
  type: git
  source:
    uri: https://github.com/c0-ops/concourse-day2-buildpacks.git
    branch: master

- name: java-buildpack-release
  type: bosh-io-release
  check_every: 2h
  source:
    repository: cloudfoundry/java-buildpack-release


jobs:

- name: update-buildpacks-java
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: concourse-day2-buildpacks
      trigger: false
    - get: java-buildpack-release
      trigger: true
  - task: update-buildpacks
    config:
      platform: linux
      image: docker:///virtmerlin/c0-worker
      inputs:
        - name: concourse-day2-buildpacks
        - name: java-buildpack-release
      run:
        path: concourse-day2-buildpacks/ci/tasks/update/update-buildpacks.sh
      params:
        buildpack: "java_buildpack_offline"
        cf_api: {{cf_api}}
        cf_user: {{cf_user}}
        cf_password: {{cf_password}}

- name: test-buildpack-java
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: concourse-day2-buildpacks
      trigger: false
      passed: [update-buildpacks-java]
    - get: java-buildpack-release
      trigger: false
      passed: [update-buildpacks-java]
  - task: test-buildpack-java
    config:
      platform: linux
      image: docker:///virtmerlin/c0-worker
      inputs:
        - name: concourse-day2-buildpacks
        - name: java-buildpack-release
      run:
        path: concourse-day2-buildpacks/ci/tasks/test/test-buildpack-java.sh
